### ISSUE TITLE
can i send / real emails with your code?  any plans for that ?

### ISSUE THREAD

**Issue by PManager1** [krasiyan/gmail-authorizer#1]

**Comment by krasiyan** [comment]
@jpca999 No, not really. This was a PoC tool to get refresh/access tokens for the Google APIs. Your best bet (if you want to use the Gmail REST APIs instead of the conventional email protocols) is to look into some modules like:

- [gmail-api-sync](https://www.npmjs.com/package/gmail-api-sync) (for reading emails)
- [gmail-send](https://www.npmjs.com/package/gmail-send) (for sending emails; basically a wrapper around [nodemailer](https://www.npmjs.com/package/nodemailer))

(I haven't tested either one of them personally)

Or you can just use the official [`googleapis`](https://www.npmjs.com/package/googleapis) Node.js client (this module uses it as well) and implement the functionality you need against the [`v1 Gmail API`](https://developers.google.com/apis-explorer/#search/gmail/gmail/v1/)
